### ISSUE TITLE
Open to Contributions?

### ISSUE THREAD

**Issue by dpchamps** [harvestwhisperer/hm64-decomp#30]
Was playing around with N64Recomp, used this project to generate an elf file, and then saw you in https://github.com/N64Recomp/N64Recomp/issues/58#issuecomment-2121521594.

Cool project :) lmk if you're open to contributions or if this is a fun personal exercise.

**Comment by harvestwhisperer** [comment]
Hey, thanks for stopping by! I'm definitely open to contributions to both matching functions and research (symbol identification)! (I'd also be interested in working on the runtime for the PC port via N64Recomp; I haven't made much progress on it on my own yet)

If it's easier, I'm also on discord at harvestwhisperer if I can field any questions about the decomp

**Comment by dpchamps** [comment]
Cool! I've poked around a bit at the runtime today and have... something compiling into a binary. Will update here if I get anything interesting running
